#!/bin/sh

docker run -d -p 5000:5000 sa-logic
docker run -d -p 8080:8080 -e "SA_LOGIC_API_URL=http://172.17.0.2:5000" sa-webapp
docker run -d -p 8085:80 sa-frontend

run app using http://localhost:30002/?webapp=http://localhost:30001