# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sa-frontend
# spec:
#   selector:
#     matchLabels:
#       app: sa-frontend
#   replicas: 3
#   minReadySeconds: 15
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
#   template:
#     metadata:
#       labels:
#         app: sa-frontend
#     spec:
#       containers:
#       - image: ameya24/sa-frontend-final
#         imagePullPolicy: Always
#         name: sa-frontend
#         ports:
#         - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-frontend
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
        - name: sa-frontend
          image: ameya24/sa-frontend-final
          ports:
            - containerPort: 80
