# apiVersion: v1
# kind: Service
# metadata:
#   name: sa-logic-lb
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 5000
#       protocol: TCP
#       targetPort: 5000
#       nodePort: 30000
#   selector:
#     app: sa-logic


apiVersion: v1
kind: Service
metadata:
  name: sa-logic-service
spec:
  type: NodePort
  selector:
    app: sa-logic
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30000