# apiVersion: v1
# kind: Service
# metadata:
#   name: sa-webapp-lb
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       protocol: TCP
#       targetPort: 8080
#       nodePort: 30001
#   selector:
#     app: sa-webapp


apiVersion: v1
kind: Service
metadata:
  name: sa-webapp-service
spec:
  type: NodePort
  selector:
    app: sa-webapp
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30001