# apiVersion: v1
# kind: Service
# metadata:
#   name: sa-logic-service
# spec:
#   type: NodePort
#   selector:
#     app: sa-logic
#   ports:
#     - port: 5000
#       targetPort: 5000
#       protocol: TCP
#       nodePort: 30000



apiVersion: v1
kind: Service
metadata:
  name: sa-logic-service
spec:
  type: LoadBalancer
  selector:
    app: sa-logic
  ports:
    - port: 5000
      targetPort: 5000
