# apiVersion: v1
# kind: Service
# metadata:
#   name: sa-webapp-service
# spec:
#   type: NodePort
#   selector:
#     app: sa-webapp
#   ports:
#     - port: 8080
#       targetPort: 8080
#       protocol: TCP
#       nodePort: 30001


apiVersion: v1
kind: Service
metadata:
  name: sa-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: sa-webapp
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP