apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-webapp
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
        - name: sa-webapp
          image: ameya24/sa-webapp-finalv1
          ports:
            - containerPort: 8080
          env:
            - name: SA_LOGIC_API_URL
              value: "http://sa-logic-service:5000"
